import type { SupabaseClient } from "@supabase/supabase-js";
import { formatDate } from "@/lib/format";
import type { ActionItem, CapitalItem, Meeting, StrategicProject, TreeItem } from "@/lib/database.types";

export async function buildBoardPacketMarkdown(
  supabase: SupabaseClient,
  meetingId: string
): Promise<string> {
  const { data: meeting } = await supabase
    .from("meetings")
    .select("*")
    .eq("id", meetingId)
    .single();

  if (!meeting) return "# Board packet\n\nMeeting not found.";

  const m = meeting as Meeting;

  const [actionsRes, treesRes, capitalRes, projectsRes, openActionsRes, feedbackRes] =
    await Promise.all([
      supabase.from("action_items").select("*").eq("source_meeting_id", meetingId),
      supabase.from("tree_items").select("*").order("updated_at", { ascending: false }).limit(40),
      supabase.from("capital_items").select("*").order("updated_at", { ascending: false }).limit(40),
      supabase
        .from("strategic_projects")
        .select("*")
        .eq("source_meeting_id", meetingId),
      supabase
        .from("action_items")
        .select("*")
        .neq("status", "Completed")
        .order("due_date", { ascending: true, nullsFirst: false })
        .limit(30),
      supabase.from("member_feedback").select("*").eq("status", "Open").limit(15),
    ]);

  const meetingActions = (actionsRes.data ?? []) as ActionItem[];
  const openActions = (openActionsRes.data ?? []) as ActionItem[];
  const trees = (treesRes.data ?? []) as TreeItem[];
  const capital = (capitalRes.data ?? []) as CapitalItem[];
  const projects = (projectsRes.data ?? []) as StrategicProject[];

  const boardActions = meetingActions.filter((a) => a.board_relevance);
  const boardTrees = trees.filter((t) =>
    /pending|notified|review/i.test(t.board_status ?? "")
  );
  const boardCapital = capital.filter(
    (c) => c.board_status?.trim() || c.status === "Under Review"
  );
  const boardProjects = projects.filter((p) => p.board_status?.trim());

  const risks = openActions.filter(
    (a) =>
      a.board_relevance &&
      a.due_date &&
      new Date(a.due_date) < new Date()
  );

  return `# Board Packet — ${m.title}
**Date:** ${formatDate(m.meeting_date)} · **Type:** ${m.meeting_type}

## Executive summary
${m.summary?.trim() || "_No summary recorded yet._"}

## Decisions requiring board awareness
${m.decisions?.trim() || "_None recorded for this meeting._"}

## Pending approvals
${[...boardActions, ...boardProjects]
  .map((x) => `- ${"title" in x ? x.title : ""}`)
  .join("\n") || "_None flagged._"}

## Tree removals / board review
${
  boardTrees.length
    ? boardTrees.map((t) => `- ${t.title} (${t.board_status})`).join("\n")
    : "_None pending._"
}

## Capital requests
${
  boardCapital.length
    ? boardCapital.map((c) => `- ${c.title} · ${c.priority} · ${c.status}`).join("\n")
    : "_None under review._"
}

## Strategic plan status
${
  projects.length
    ? projects.map((p) => `- ${p.title} — ${p.status}${p.board_status ? ` (board: ${p.board_status})` : ""}`).join("\n")
    : "_No projects sourced from this meeting._"
}

## Open risks / blockers
${
  risks.length
    ? risks.map((a) => `- ${a.title} (overdue)`).join("\n")
    : "_None identified._"
}

## Member communication
${
  (feedbackRes.data ?? []).length
    ? (feedbackRes.data ?? [])
        .map((f: { topic: string; status: string }) => `- ${f.topic} (${f.status})`)
        .join("\n")
    : "_No open feedback items._"
}

## Open action items (committee-wide)
${
  openActions.slice(0, 15).length
    ? openActions
        .slice(0, 15)
        .map(
          (a) =>
            `- ${a.title} | ${a.owner ?? "—"} | ${a.status} | due ${formatDate(a.due_date)}`
        )
        .join("\n")
    : "_None._"
}

---
_Generated by MCCC Greens OS — copy and edit for board distribution._
`;
}
